baseURL = "https://happymaybe.com/"
languageCode = "en-us"
title = "Happy Maybe Podcast"
theme = "ink-free"
paginate = 99

copyright = "© Copyright"

[permalinks]
  posts = "/:year/:month/:title"

[params]
	subtitle = "A conversational podcast where Vasily and Nikita share their unique insights on the winding journey of life."

	# podcast artwork image
	ogimage = "/images/happy-maybe-artwork-1.jpg"

	# Optional 64x64 avatar image.
	#avatar = "https://image.freepik.com/free-vector/young-man-head-with-beard-avatar-character_24877-36786.jpg"

	featherIconsCDN = false

	# Site color - dark/light/auto
	mode = "auto"

	customCSS = "css/enhance.css"
	# customDarkCSS = "css/enhance-dark.css"

	# Enable a table of contents
	toc = true

	# Max tags
	maxTags = 7

	# Define words per minute to approximate reading time
	wpm = 250

	# Stupid footers :)
	footers = [ 
		"What Tiger King can teach us about x86 Assembly",
		"10 Reasons why gcc SHOULD be re-written in JavaScript - You won't believe #8!"
	]

	# Github base url
	github = "https://github.com/nchepanov/happymaybe.com"


# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "github"
    tabWidth = 4

  [markup.tableOfContents]
    endLevel = 3
    ordered = true
    startLevel = 2 
